BlogApp.WebUI/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BlogApp.Data.Abstract;
using BlogApp.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BlogApp.WebUI.Controllers
{
    public class BlogController : Controller
    {
        private IBlogRepository blogRepository;
        private ICategoryRepository categoryRepository;
        public BlogController(IBlogRepository _blogRepository, ICategoryRepository _categoryRepository)
        {
            blogRepository = _blogRepository;
            categoryRepository = _categoryRepository;
        }

        public IActionResult Index(int? id,string q)
        {
            if (id == null)
            {
                if (!string.IsNullOrEmpty(q))
                {
                    return View(blogRepository.GetAll().Where(i=>i.isApproved).Where(i => i.Title.Contains(q) || i.Description.Contains(q) || i.Body.Contains(q)).OrderByDescending(i => i.Date));
                }
                return View(blogRepository.GetAll().Where(i => i.isApproved).OrderByDescending(i => i.Date));
            }
            else
            {
                if (!string.IsNullOrEmpty(q))
                {
                    return View(blogRepository.GetAll().Where(i => i.isApproved).Where(i => i.Title.Contains(q) || i.Description.Contains(q) || i.Body.Contains(q)).OrderByDescending(i => i.Date));
                }
                return View(blogRepository.GetAll().Where(i => i.isApproved && i.CategoryId == id).OrderByDescending(i => i.Date));
            }
            
            
        }

        public IActionResult List()
        {
            return View(blogRepository.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(categoryRepository.GetAll(), "CategoryId", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Blog model,IFormFile file)
        {
            if(file != null)
            {
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", file.FileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
                model.Image = file.FileName;
            }
            
            model.Date = DateTime.Now;
            if (ModelState.IsValid)
            {
                blogRepository.AddBlog(model);
                return RedirectToAction("List");
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var blog = blogRepository.GetById(id);
            ViewBag.Categories = new SelectList(categoryRepository.GetAll(), "CategoryId", "Name");
            return View(blog);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Blog model,IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", file.FileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                    model.Image = file.FileName;
                }
                
                blogRepository.UpdateBlog(model);
                TempData["message"] = $"{model.Title} güncellendi.";
                return RedirectToAction("List");
            }
            ViewBag.Categories = new SelectList(categoryRepository.GetAll(), "CategoryId", "Name");
            return View(model);
        }

        public IActionResult Delete(int id)
        {
            TempData["message"] = $"{blogRepository.GetById(id).Title} silindi.";
            blogRepository.DeleteBlog(id);
            return RedirectToAction("List");
        }

        public IActionResult Detail(int id)
        {
            return View(blogRepository.GetById(id));
        }
    }
}

BlogApp.WebUI/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogApp.Data.Abstract;
using BlogApp.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BlogApp.WebUI.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryRepository categoryRepository;
        private IBlogRepository blogRepository;
        public CategoryController(ICategoryRepository _categoryRepository, IBlogRepository _blogRepository)
        {
            categoryRepository = _categoryRepository;
            blogRepository = _blogRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List()
        {
            return View(categoryRepository.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category model)
        {
            if (ModelState.IsValid)
            {
                categoryRepository.AddCategory(model);
                return RedirectToAction("List");
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult AddUpdate(int? id)
        {
            if(id == null) {
            return View(new Category());
            }
            else
            {
                var category = categoryRepository.GetById((int)id);
                return View(category);
            }
        }

        [HttpPost]
        public IActionResult AddUpdate(Category model)
        {
            if (ModelState.IsValid)
            {
                categoryRepository.SaveCategory(model);
                TempData["message"] = $"{model.Name} kayıt edildi.";
                return RedirectToAction("List");
            }
            return View(model);
        }

        public IActionResult Delete(int id)
        {
            TempData["message"] = $"{categoryRepository.GetById(id).Name} silindi.";
            categoryRepository.DeleteCategory(id);
            return RedirectToAction("List");
        }
    }
}

BlogApp.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogApp.Data.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace BlogApp.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private IBlogRepository blogRepository;

        public HomeController(IBlogRepository _blogRepository)
        {
            blogRepository = _blogRepository;
        }

        public IActionResult Index()
        {
            return View(blogRepository.GetAll().Where(i=>i.isApproved && i.isHome));
        }

        public IActionResult List()
        {
            return View();
        }
        
        public IActionResult Detail()
        {
            return View();
        }
    }
}

BlogApp.WebUI/ViewComponents/CategoryMenuViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogApp.Data.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace BlogApp.WebUI.ViewComponents
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        public ICategoryRepository categoryRepository;

        public CategoryMenuViewComponent(ICategoryRepository _categoryRepository)
        {
            categoryRepository = _categoryRepository;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["id"];
            return View(categoryRepository.GetAll());
        }
    }
}

BlogApp.WebUI/Views/Blog/Create.cshtml
@model Blog
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container mt-2">
    <h2>Create</h2>

    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="Description">Description</label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>

        <div class="form-group">
            <label asp-for="Body">Body</label>
            <input asp-for="Body" class="form-control" />
        </div>

        <div class="form-group">
            <label>Image</label>
            <input type="file" name="file" id="file" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="CategoryId">Category</label>
            <select asp-for="CategoryId" asp-items="ViewBag.Categories" class="form-control">
                <option disabled selected value="">Select Category</option>
            </select>
        </div>

        <div class="form-check">
            <label asp-for="isApproved" class="form-check-label">
                <input asp-for="isApproved" type="checkbox" class="form-check-input" />
                İs Approved
            </label>
        </div>
        <div class="form-check">
            <label asp-for="isHome" class="form-check-label">
                <input asp-for="isHome" type="checkbox" class="form-check-input" />
                İs Home
            </label>
        </div><br />
        <button type="submit" class="btn btn-primary">Submit</button>

    </form>
</div>

BlogApp.WebUI/Views/Blog/Detail.cshtml
@model Blog
@{
    ViewData["Title"] = "Detail";
}

<div class="container mt-3">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    @Model.Title
                </div>
                <img class="card-img-top" src="~/img/1.jpeg" alt="@Model.Title">
                <div class="card-body">
                    <h5 class="card-title">@Model.Title</h5>
                    <p class="card-text">@Model.Description</p>
                    <p class="card-text">@Html.Raw(Model.Body)</p>
                </div>
            </div>
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Blog/Index.cshtml
@model IEnumerable<Blog>
@{
    ViewData["Title"] = "Index";
}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">
            @Html.Partial("_BlogList", Model)
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Blog/List.cshtml
@model IEnumerable<Blog>
@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container mt-3">
    <h2>List</h2><br />
    <div class="row">
        <div class="col">
            @if (Model.Count() > 0)
            {
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <td>Id</td>
                            <td>Image</td>
                            <td>Title</td>
                            <td>Date</td>
                            <td>Is Approved</td>
                            <td>Is Home</td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>@item.BlogId</td>
                            <td><img src="~/img/@item.Image" width="100" /></td>
                            <td>@item.Title</td>
                            <td>@item.Date</td>
                            <td>
                                @if (@item.isApproved)
                                {
                                    <i class="fa fa-check" aria-hidden="true"></i>
                                }
                                else
                                {
                                    <i class="fa fa-times" aria-hidden="true"></i>
                                }
                            </td>
                            <td>
                                @if (@item.isHome)
                                {
                                    <i class="fa fa-check" aria-hidden="true"></i>
                                }
                                else
                                {
                                    <i class="fa fa-times" aria-hidden="true"></i>
                                }
                            </td>
                            <td>
                                <a class="btn btn-primary btn-sm" asp-controller="Blog" asp-action="Update" asp-route-id="@item.BlogId">Update</a>
                                <a class="btn btn-sm bg-danger text-white" data-toggle="confirmation" data-title="Are You Sure?" data-btn-ok-label="Yes" data-btn-ok-class="btn-danger"
                                   data-btn-cancel-label="No" asp-controller="Blog" asp-action="Delete" asp-route-id="@item.BlogId">Delete</a>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>

            }
            else
            {
                <div class="glyphicon-alert alert-danger">
                    Blog Eklenmemiş.
                </div>

            }
            <a class="btn btn-success" asp-action="Create">New Blog</a>
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Blog/Update.cshtml
@model Blog
@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section scripts{ 
<script src="~/vendor/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace("Body");
    </script>
}

<div class="container mt-2">
    <h2>Update Blog</h2>

    <form method="post" enctype="multipart/form-data">
        <input type="hidden" asp-for="BlogId" />
        <input type="hidden" asp-for="Image" />
        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="Description">Description</label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>

        <div class="form-group">
            <label asp-for="Body">Body</label>
            <textarea asp-for="Body" class="form-control"></textarea>
        </div>

        <div class="form-group">
            <label>Image</label><br />
            <img src="~/img/@Model.Image" style="width:120px" />
            <input type="file" name="file" id="file" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="CategoryId">Category</label>
            <select asp-for="CategoryId" asp-items="ViewBag.Categories" class="form-control">
                <option disabled selected value="">Select Category</option>
            </select>
        </div>
        <div class="form-check">
            <label asp-for="isApproved" class="form-check-label">
                <input asp-for="isApproved" type="checkbox" class="form-check-input" />
                İs Approved
            </label>
        </div>
        <div class="form-check">
            <label asp-for="isHome" class="form-check-label">
                <input asp-for="isHome" type="checkbox" class="form-check-input" />
                İs Home
            </label>
        </div><br />
        <button type="submit" class="btn btn-primary">Submit</button>

    </form>
</div>

BlogApp.WebUI/Views/Category/AddUpdate.cshtml
@model Category
@{
    ViewData["Title"] = "AddUpdate";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="container mt-2">
    <h2>Save Category</h2>

    <form method="post">
        <input type="hidden" asp-for="CategoryId" />
        <div class="form-group">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>

    </form>
</div>

BlogApp.WebUI/Views/Category/Create.cshtml
@model Category
@{
    ViewData["Title"] = "Create Category";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container mt-2">
    <h2>Create Category</h2>

    <form method="post">
        <div class="form-group">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>

    </form>
</div>

BlogApp.WebUI/Views/Category/List.cshtml
@model IEnumerable<Category>
@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container mt-3">
    <h2>Category</h2><br />
    <div class="row">
        <div class="col">
            @if (Model.Count() > 0)
            {
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <td>Id</td>
                            <td>Name</td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.CategoryId</td>
                                <td>@item.Name</td>
                                <td>
                                    <a class="btn btn-primary btn-sm" asp-controller="Category" asp-action="AddUpdate" asp-route-id="@item.CategoryId">Details</a>
                                    <a class="btn btn-sm bg-danger text-white" data-toggle="confirmation" data-title="Are You Sure?" data-btn-ok-label="Yes" data-btn-ok-class="btn-danger"
                                       data-btn-cancel-label="No" asp-controller="Category" asp-action="Delete" asp-route-id="@item.CategoryId">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            }
            else
            {
                <div class="glyphicon-alert alert-danger">
                    Blog Eklenmemiş.
                </div>

            }
            <a class="btn btn-success" asp-action="AddUpdate">New Category</a>
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Home/Detail.cshtml
@{
    ViewData["Title"] = "Detail";
}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">
            <div class="card">
                <div class="card-header">
                    Featured
                </div>
                <img class="card-img-top" src="~/img/1.jpeg" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Home/Index.cshtml
@model IEnumerable<Blog>
@{
    ViewData["Title"] = "Index";
}

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Hello, world!</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            @await  Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">
            @Html.Partial("_BlogList",Model)
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Home/List.cshtml
@{
    ViewData["Title"] = "List";
}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">
            <div class="card">
                <div class="card-header">
                    Featured
                </div>
                <img class="card-img-top" src="~/img/1.jpeg" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
            <div class="card mt-2">
                <div class="card-header">
                    Featured
                </div>
                <img class="card-img-top" src="~/img/2.jpeg" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
            <div class="card mt-2">
                <div class="card-header">
                    Featured
                </div>
                <img class="card-img-top" src="~/img/3.jpeg" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
            <div class="card mt-2">
                <div class="card-header">
                    Featured
                </div>
                <img class="card-img-top" src="~/img/4.jpeg" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>

<div class="list-group">
    @foreach (var item in Model)
    {
        <a asp-action="Index" asp-route-id="@item.CategoryId" class="list-group-item list-group-item-action @(ViewBag.SelectedCategory==item.CategoryId.ToString()?"active ":"" ))">
            @item.Name
        </a>
    }


</div>

BlogApp.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">BlogApp</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">User Page <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/blog">Blogs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/blog/list">Blog List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/category/list">Category List</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <div class="mb-3">
        <div class="container">
            @if (TempData["message"] != null)
            {
                <div class="alert alert-success mt-2">
                    @TempData["message"]
                </div>
            }
        </div>
        @RenderBody()
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="~/node_modules/tether/dist/js/tether.min.js"></script>
    <script src="~/js/script.js"></script>
    <script src="~/js/popover.js"></script>
    <script src="~/js/bootstrap-confirmation.min.js"></script>
    <script>$('[data-toggle="confirmation"]').confirmation();</script>
    @RenderSection("scripts", false);
</body>
</html>

BlogApp.WebUI/Views/Shared/_BlogList.cshtml
@model IEnumerable<Blog>

@if (Model.Count() == 0)
{
    <div class=" alert alert-warning">No Blog</div>

}

@foreach (var item in Model)
{
    <div class="card mb-2">
        <div class="card-header">
            @item.Title
        </div>
        <img class="card-img-top" src="~/img/@item.Image" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">@item.Title</h5>
            <p class="card-text">@item.Description</p>
            <a asp-controller="Blog" asp-action="Detail" asp-route-id="@item.BlogId" class="btn btn-primary">Blog Details</a>
        </div>
    </div>
}

BlogApp.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">BlogApp</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">HomePage <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/blog">Blogs</a>
                    </li>
                </ul>
                <form asp-controller="Blog" asp-action="Index" method="get" class="form-inline my-2 my-lg-0">
                    <input id="q" name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <div class="mb-3">
        <div class="container">
            @if (TempData["message"] != null)
            {
                <div class="alert alert-success mt-2">
                    @TempData["message"]
                </div>
            }
        </div>
        @RenderBody()
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="~/node_modules/tether/dist/js/tether.min.js"></script>
    <script src="~/js/script.js"></script>
    <script src="~/js/popover.js"></script>
    <script src="~/js/bootstrap-confirmation.min.js"></script>
    <script>$('[data-toggle="confirmation"]').confirmation();</script>
    @RenderSection("scripts", false);
</body>
</html>